[package]
name = "logix-type"
version = "0.1.0"
description = "Provides the `LogixType` trait and the parser for `.logix` files, aimed at enabling easy-to-read-and-write configurations for `logix`."
repository = "https://github.com/logix-tool/logix-loom"
edition = "2021"
authors = [
  "Bjørn Ove Hay Andersen <bjrnove@gmail.com>",
  "Gigantos <gigantos@gigantos.net>",
]
readme = "README.md"
license = "MPL-2.0"
categories = ["parsing", "config", "parser-implementations"]

[dependencies]
bstr = "1.7.0"
indexmap = "2.0.2"
logix-type-derive = { path = "derive" }
logix-vfs = "0.4.0"
owo-colors = { version = "4.0.0-rc.1", features = ["alloc"] }
smol_str = "0.2.0"
thiserror = "1.0.49"

[dev-dependencies]
tempfile = "3.8.0"

[workspace]
members = [
  "derive"
]
