[package]
name = "logix-mold"
version = "0.1.0"
description = "Parser for .logix files, aimed at enabling easy-to-read-and-write configurations for the Logix tool."
repository = "https://github.com/logix-tool/logix-loom"
edition = "2021"
authors = [
  "Bjørn Ove Hay Andersen <bjrnove@gmail.com>",
  "Gigantos <gigantos@gigantos.net>",
]
readme = "README.md"
license = "MPL-2.0"
categories = ["parsing", "config", "parser-implementations"]

[dependencies]
bstr = "1.7.0"
logix-mold-derive = { path = "derive" }
logix-vfs = "0.2.0"
miette = "5.10.0"
smol_str = "0.2.0"
thiserror = "1.0.49"

[dev-dependencies]
tempfile = "3.8.0"

[workspace]
members = [
  "derive"
]
